server:
  port: 8080
spring:
  application:
    name: maven-springboot
  datasource:
    url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
antoa:
  config:
    home_page: 
    login_diy: false
    menu_routes:
       - name: 首页
         home: true
       - name: 用户管理
         role_limit_id: 1
         children: 
             - path: /admin/user/list
               name: 用户列表
               role_limit_id: 1
             -
               visible: false
               path: /admin/user/edit
               name: 用户编辑
               role_limit_id: 1
    qiniu:
      access_key: QiniuAccessKey
      secret_key: QiniuSecretKey
      bucket: Bucket
      url: http://xxx.xxx.com/
    template_file_path: template